
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDECOMMA DIVIDE ELSE EQ FOR HEADER ID IF INCLUDE INT LBRACE LPAREN MAIN MINUS NUMBER PLUS PRINTF RBRACE RETURN RPAREN SEMI TIMES WHILEprogram : includes functions\n               | includes\n               | functionsincludes : includes include\n                | includeinclude : INCLUDE HEADERfunctions : functions function\n                 | functionfunction : type ID LPAREN RPAREN LBRACE statements RBRACEtype : INTstatements : statements statement\n                  | statementstatement : declaration\n                 | assignment\n                 | loop\n                 | RETURN expression SEMIdeclaration : type ID EQ expression SEMIassignment : ID EQ expression SEMIloop : FOR LPAREN assignment expression SEMI assignment RPAREN LBRACE statements RBRACEexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expression\n                  | NUMBER\n                  | ID'
    
_lr_action_items = {'INCLUDE':([0,2,4,10,12,],[6,6,-5,-4,-6,]),'INT':([0,2,3,4,5,9,10,11,12,16,19,20,21,22,23,28,29,36,43,49,53,54,55,],[8,8,8,-5,-8,8,-4,-7,-6,8,8,-12,-13,-14,-15,-9,-11,-16,-18,-17,8,8,-19,]),'$end':([1,2,3,4,5,9,10,11,12,28,],[0,-2,-3,-5,-8,-1,-4,-7,-6,-9,]),'HEADER':([6,],[12,]),'ID':([7,8,16,17,19,20,21,22,23,24,27,29,33,34,36,37,38,39,40,41,43,49,50,53,54,55,],[13,-10,18,26,18,-12,-13,-14,-15,32,32,-11,18,32,-16,32,32,32,32,32,-18,-17,18,18,18,-19,]),'LPAREN':([13,25,],[14,33,]),'RPAREN':([14,43,51,],[15,-18,52,]),'LBRACE':([15,52,],[16,53,]),'RETURN':([16,19,20,21,22,23,29,36,43,49,53,54,55,],[24,24,-12,-13,-14,-15,-11,-16,-18,-17,24,24,-19,]),'FOR':([16,19,20,21,22,23,29,36,43,49,53,54,55,],[25,25,-12,-13,-14,-15,-11,-16,-18,-17,25,25,-19,]),'EQ':([18,26,],[27,34,]),'RBRACE':([19,20,21,22,23,29,36,43,49,54,55,],[28,-12,-13,-14,-15,-11,-16,-18,-17,55,-19,]),'NUMBER':([24,27,34,37,38,39,40,41,43,],[31,31,31,31,31,31,31,31,-18,]),'SEMI':([30,31,32,35,42,44,45,46,47,48,],[36,-24,-25,43,49,-20,-21,-22,-23,50,]),'PLUS':([30,31,32,35,42,44,45,46,47,48,],[37,-24,-25,37,37,-20,-21,-22,-23,37,]),'MINUS':([30,31,32,35,42,44,45,46,47,48,],[38,-24,-25,38,38,-20,-21,-22,-23,38,]),'TIMES':([30,31,32,35,42,44,45,46,47,48,],[39,-24,-25,39,39,39,39,-22,-23,39,]),'DIVIDE':([30,31,32,35,42,44,45,46,47,48,],[40,-24,-25,40,40,40,40,-22,-23,40,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'includes':([0,],[2,]),'functions':([0,2,],[3,9,]),'include':([0,2,],[4,10,]),'function':([0,2,3,9,],[5,5,11,11,]),'type':([0,2,3,9,16,19,53,54,],[7,7,7,7,17,17,17,17,]),'statements':([16,53,],[19,54,]),'statement':([16,19,53,54,],[20,29,20,29,]),'declaration':([16,19,53,54,],[21,21,21,21,]),'assignment':([16,19,33,50,53,54,],[22,22,41,51,22,22,]),'loop':([16,19,53,54,],[23,23,23,23,]),'expression':([24,27,34,37,38,39,40,41,],[30,35,42,44,45,46,47,48,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> includes functions','program',2,'p_program','app.py',80),
  ('program -> includes','program',1,'p_program','app.py',81),
  ('program -> functions','program',1,'p_program','app.py',82),
  ('includes -> includes include','includes',2,'p_includes','app.py',89),
  ('includes -> include','includes',1,'p_includes','app.py',90),
  ('include -> INCLUDE HEADER','include',2,'p_include','app.py',97),
  ('functions -> functions function','functions',2,'p_functions','app.py',101),
  ('functions -> function','functions',1,'p_functions','app.py',102),
  ('function -> type ID LPAREN RPAREN LBRACE statements RBRACE','function',7,'p_function','app.py',109),
  ('type -> INT','type',1,'p_type','app.py',113),
  ('statements -> statements statement','statements',2,'p_statements','app.py',117),
  ('statements -> statement','statements',1,'p_statements','app.py',118),
  ('statement -> declaration','statement',1,'p_statement','app.py',125),
  ('statement -> assignment','statement',1,'p_statement','app.py',126),
  ('statement -> loop','statement',1,'p_statement','app.py',127),
  ('statement -> RETURN expression SEMI','statement',3,'p_statement','app.py',128),
  ('declaration -> type ID EQ expression SEMI','declaration',5,'p_declaration','app.py',132),
  ('assignment -> ID EQ expression SEMI','assignment',4,'p_assignment','app.py',136),
  ('loop -> FOR LPAREN assignment expression SEMI assignment RPAREN LBRACE statements RBRACE','loop',10,'p_loop','app.py',140),
  ('expression -> expression PLUS expression','expression',3,'p_expression','app.py',144),
  ('expression -> expression MINUS expression','expression',3,'p_expression','app.py',145),
  ('expression -> expression TIMES expression','expression',3,'p_expression','app.py',146),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression','app.py',147),
  ('expression -> NUMBER','expression',1,'p_expression','app.py',148),
  ('expression -> ID','expression',1,'p_expression','app.py',149),
]
